/**
 * Slack Notification Utility
 * Zero-dependency — uses built-in Node.js https module.
 * Reads Allure summary.json for test counts and sends a color-coded message.
 *
 * Required env vars:
 *   SLACK_WEBHOOK_URL — Slack incoming webhook URL
 *   GITHUB_RUN_URL   — Link to the GitHub Actions run
 *   REPORT_URL       — Link to the published Allure report
 *
 * Optional env vars:
 *   TEST_OUTCOME     — 'success' | 'failure' (from GH Actions step outcome)
 *   HEAL_ENABLED     — whether AI healing was enabled
 */

const https = require('https');
const http = require('http');
const fs = require('fs');
const path = require('path');
const runtime = require('../config/runtime.config');

function loadSummary() {
  // Try 1: standard allure-report directory
  const summaryPath = path.resolve(process.cwd(), 'allure-report', 'widgets', 'summary.json');
  try {
    return JSON.parse(fs.readFileSync(summaryPath, 'utf8'));
  } catch { /* not found */ }

  // Try 2: latest report in allure-reports-history/ (generated by allure-auto-reporter)
  const historyDir = path.resolve(process.cwd(), 'allure-reports-history');
  try {
    const folders = fs.readdirSync(historyDir)
      .filter(f => f.startsWith('allure-report-'))
      .sort()
      .reverse();
    if (folders.length > 0) {
      const latestSummary = path.join(historyDir, folders[0], 'widgets', 'summary.json');
      return JSON.parse(fs.readFileSync(latestSummary, 'utf8'));
    }
  } catch { /* not found */ }

  // Try 3: build summary directly from allure-results JSON files
  const resultsDir = path.resolve(process.cwd(), 'allure-results');
  try {
    const files = fs.readdirSync(resultsDir).filter(f => f.endsWith('-result.json'));
    if (files.length > 0) {
      const statistic = { passed: 0, failed: 0, broken: 0, skipped: 0, unknown: 0, total: 0 };
      let minStart = Infinity, maxStop = 0;
      for (const file of files) {
        const r = JSON.parse(fs.readFileSync(path.join(resultsDir, file), 'utf8'));
        const status = r.status || 'unknown';
        statistic[status] = (statistic[status] || 0) + 1;
        statistic.total++;
        if (r.start && r.start < minStart) minStart = r.start;
        if (r.stop && r.stop > maxStop) maxStop = r.stop;
      }
      console.log('[SlackNotify] Built summary from allure-results files');
      return { statistic, time: { duration: maxStop - minStart } };
    }
  } catch { /* not found */ }

  return null;
}

function buildMessage(summary) {
  const outcome = process.env.TEST_OUTCOME || (summary && summary.statistic && summary.statistic.failed === 0 ? 'success' : 'unknown');
  const passed = outcome === 'success';
  const color = passed ? '#2eb886' : '#e01e5a';
  const icon = passed ? ':large_green_circle:' : ':red_circle:';
  const status = passed ? 'ALL TESTS PASSED' : 'TESTS FAILED';

  const runUrl = process.env.GITHUB_RUN_URL || '';
  const reportUrl = process.env.REPORT_URL || '';
  const healEnabled = process.env.HEAL_ENABLED === 'true' || runtime.ai.healingEnabled;
  const timestamp = new Date().toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' });

  // Build stats
  let total = 0, pass = 0, fail = 0, broken = 0, skipped = 0;
  if (summary && summary.statistic) {
    const s = summary.statistic;
    total = s.total || 0;
    pass = s.passed || 0;
    fail = s.failed || 0;
    broken = s.broken || 0;
    skipped = s.skipped || 0;
  }

  let duration = 'N/A';
  if (summary && summary.time) {
    const ms = summary.time.duration || 0;
    const seconds = Math.round(ms / 1000);
    const min = Math.floor(seconds / 60);
    const sec = seconds % 60;
    duration = min > 0 ? `${min}m ${sec}s` : `${sec}s`;
  }

  // Build the stats line with emoji indicators
  const statsLine = total > 0
    ? `:white_check_mark: ${pass}  :x: ${fail}  :warning: ${broken}  :fast_forward: ${skipped}  |  *${total} total*`
    : '_No test results available (run tests first)_';

  // Progress bar visualization
  let progressBar = '';
  if (total > 0) {
    const passRatio = Math.round((pass / total) * 10);
    const failRatio = Math.round((fail / total) * 10);
    const rest = 10 - passRatio - failRatio;
    progressBar = '\u2705'.repeat(passRatio) + '\u274C'.repeat(failRatio) + '\u2B1C'.repeat(Math.max(0, rest));
  }

  const blocks = [
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `${icon}  *${status}*\n_Playwright Smoke Suite_`,
      },
    },
    { type: 'divider' },
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Test Results*\n${statsLine}${progressBar ? '\n' + progressBar : ''}`,
      },
    },
    {
      type: 'section',
      fields: [
        { type: 'mrkdwn', text: `*:clock1: Duration*\n${duration}` },
        { type: 'mrkdwn', text: `*:gear: Environment*\n\`${runtime.mode.toUpperCase()}\`` },
        { type: 'mrkdwn', text: `*:robot_face: AI Healing*\n${healEnabled ? ':white_check_mark: Active' : ':no_entry_sign: Disabled'}` },
        { type: 'mrkdwn', text: `*:calendar: Executed*\n${timestamp}` },
      ],
    },
  ];

  // Add action buttons only when URLs exist
  if (runUrl || reportUrl) {
    blocks.push({ type: 'divider' });
    blocks.push({
      type: 'actions',
      elements: [
        ...(runUrl ? [{ type: 'button', text: { type: 'plain_text', text: ':github: View Pipeline Run', emoji: true }, url: runUrl }] : []),
        ...(reportUrl ? [{ type: 'button', text: { type: 'plain_text', text: ':bar_chart: Allure Report', emoji: true }, url: reportUrl, style: 'primary' }] : []),
      ],
    });
  }

  // Add footer context
  blocks.push({
    type: 'context',
    elements: [
      { type: 'mrkdwn', text: `_Sent by QA Playwright Execution Pipeline  •  Browser: ${runtime.browser.channel}  •  Headless: ${runtime.browser.headless}_` },
    ],
  });

  return {
    text: `${icon} ${status} — Passed: ${pass}, Failed: ${fail}, Total: ${total}`,
    attachments: [
      {
        color,
        fallback: `${icon} ${status} — Passed: ${pass}, Failed: ${fail}, Total: ${total}`,
        blocks,
      },
    ],
  };
}

function sendWebhook(webhookUrl, payload) {
  return new Promise((resolve, reject) => {
    const url = new URL(webhookUrl);
    const transport = url.protocol === 'https:' ? https : http;
    const data = JSON.stringify(payload);

    const options = {
      hostname: url.hostname,
      port: url.port || (url.protocol === 'https:' ? 443 : 80),
      path: url.pathname + url.search,
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Content-Length': Buffer.byteLength(data),
      },
    };

    const req = transport.request(options, (res) => {
      let body = '';
      res.on('data', (chunk) => (body += chunk));
      res.on('end', () => {
        if (res.statusCode >= 200 && res.statusCode < 300) {
          resolve(body);
        } else {
          reject(new Error(`Slack responded with ${res.statusCode}: ${body}`));
        }
      });
    });

    req.on('error', reject);
    req.write(data);
    req.end();
  });
}

async function main() {
  if (!runtime.reporting.slackEnabled) {
    console.log('[SlackNotify] Slack notifications disabled in runtime config — skipping.');
    process.exit(0);
  }

  const webhookUrl = runtime.reporting.slackWebhookUrl || process.env.SLACK_WEBHOOK_URL;
  if (!webhookUrl) {
    console.log('[SlackNotify] SLACK_WEBHOOK_URL not set — skipping notification.');
    process.exit(0);
  }

  const summary = loadSummary();
  const payload = buildMessage(summary);

  try {
    const response = await sendWebhook(webhookUrl, payload);
    console.log(`[SlackNotify] Notification sent successfully. Response: ${response}`);
  } catch (err) {
    console.error('[SlackNotify] Failed to send notification:', err.message);
    process.exit(1);
  }
}

main();
